// src/lib/pdf.ts
import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage, PDFImage } from "pdf-lib";
import fs from "fs";
import path from "path";

export type TableSpec = {
  title: string;
  columns: { key: string; header: string; width: number }[]; // width in points
  rows: Record<string, string | number | null | undefined>[];
  footerNote?: string;
};

type HeaderSpec = {
  titleLeft: string;
  titleRight?: string;
  subtitle?: string;
};

type FontSet = {
  font: PDFFont;
  bold: PDFFont;
  logoImage?: PDFImage | null;
};

export async function createPdfDoc(): Promise<{
  doc: PDFDocument;
  font: PDFFont;
  bold: PDFFont;
  logoImage: PDFImage | null;
}> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  // Load Benefits Booster logo if available
  let logoImage: PDFImage | null = null;
  const logoPath = path.join(process.cwd(), "public", "benefits-booster-logo.png");
  if (fs.existsSync(logoPath)) {
    try {
      const logoBytes = fs.readFileSync(logoPath);
      logoImage = await doc.embedPng(logoBytes);
    } catch (e) {
      console.log("Logo not found, skipping");
    }
  }

  return { doc, font, bold, logoImage };
}

export function addPage(doc: PDFDocument): PDFPage {
  return doc.addPage([612, 792]); // Letter (portrait)
}

export function drawHeaderFooter(page: PDFPage, fonts: FontSet, header: HeaderSpec): void {
  const { font, bold, logoImage } = fonts;
  const { width, height } = page.getSize();
  const margin = 36;

  // Colors matching Benefits Booster theme
  const primaryBlue = rgb(0.05, 0.32, 0.62); // #0D5280
  const accentRed = rgb(0.8, 0.1, 0.1);
  const textGray = rgb(0.2, 0.2, 0.2);

  let headerY = height - margin;

  // Logo and branding at top
  if (logoImage) {
    const logoWidth = 60;
    const logoHeight = 36;
    page.drawImage(logoImage, {
      x: margin,
      y: headerY - logoHeight,
      width: logoWidth,
      height: logoHeight,
    });
    // Add tagline below logo in red
    page.drawText("Making your benefits soar", {
      x: margin,
      y: headerY - logoHeight - 12,
      size: 8,
      font: font,
      color: accentRed,
    });
    headerY -= logoHeight + 20;
  } else {
    // Draw text logo if image not available
    page.drawText("Benefits Booster", {
      x: margin,
      y: headerY,
      size: 14,
      font: bold,
      color: primaryBlue,
    });
    page.drawText("Making your benefits soar", {
      x: margin,
      y: headerY - 16,
      size: 8,
      font: font,
      color: accentRed,
    });
    headerY -= 30;
  }

  // Header line
  page.drawLine({ start: { x: margin, y: headerY }, end: { x: width - margin, y: headerY }, thickness: 1, color: rgb(0.85,0.88,0.92) });
  headerY -= 20;

  // Title
  page.drawText(header.titleLeft, { x: margin, y: headerY, size: 14, font: bold, color: textGray });

  if (header.titleRight) {
    const textWidth = bold.widthOfTextAtSize(header.titleRight, 12);
    page.drawText(header.titleRight, { x: width - margin - textWidth, y: headerY, size: 12, font, color: rgb(0.25,0.28,0.35) });
  }
  if (header.subtitle) {
    page.drawText(header.subtitle, { x: margin, y: headerY - 18, size: 10, font, color: rgb(0.35,0.38,0.45) });
  }

  // Footer
  page.drawLine({ start: { x: margin, y: margin + 22 }, end: { x: width - margin, y: margin + 22 }, thickness: 1, color: rgb(0.85,0.88,0.92) });
  page.drawText("Generated by Benefits Booster", { x: margin, y: margin + 8, size: 9, font, color: rgb(0.35,0.38,0.45) });
}

export function drawTable(opts: {
  page: PDFPage;
  fonts: { font: PDFFont; bold: PDFFont };
  table: TableSpec;
  topY: number; // starting Y
}): { nextY: number; exhausted: boolean } {
  const { page, fonts, table, topY } = opts;
  const { font, bold } = fonts;
  const { width } = page.getSize();
  const margin = 36;
  const rowH = 18;
  const headerH = 22;
  const minY = 72; // margin + footer area

  let y = topY;

  // Title
  page.drawText(table.title, { x: margin, y: y - 2, size: 12, font: bold, color: rgb(0.12,0.14,0.18) });
  y -= 22;

  // Header row background
  page.drawRectangle({ x: margin, y: y - headerH + 4, width: width - margin * 2, height: headerH, color: rgb(0.95,0.96,0.98) });

  // Column headers
  let x = margin + 6;
  for (const col of table.columns) {
    page.drawText(col.header, { x, y: y, size: 10, font: bold, color: rgb(0.25,0.28,0.35) });
    x += col.width;
  }
  y -= headerH + 2;

  // Rows
  for (const r of table.rows) {
    // Check pagination
    if (y < minY + rowH) {
      // signal caller we ran out of space
      return { nextY: y, exhausted: true };
    }
    let cx = margin + 6;
    for (const col of table.columns) {
      const val = r[col.key];
      const text = val === null || typeof val === "undefined" ? "—" : String(val);
      page.drawText(text, { x: cx, y, size: 10, font, color: rgb(0.1,0.12,0.16) });
      cx += col.width;
    }
    y -= rowH;
  }

  if (table.footerNote) {
    if (y < minY + rowH) {
      return { nextY: y, exhausted: true };
    }
    page.drawText(table.footerNote, { x: margin, y: y - 6, size: 9, font, color: rgb(0.35,0.38,0.45) });
    y -= rowH;
  }

  return { nextY: y, exhausted: false };
}
